### ISSUE TITLE
Documentação da página oficial

### ISSUE THREAD

**Issue by dzonen** [shipping7/correios-java-sdk#101]
A documentação na página oficial do SDK sugere o exemplo:

CorreiosCredentials credentials = new CorreiosCredentials("username", "password");

Porém o correto seria:

CorreiosCredenciais credenciais = new CorreiosCredenciais("username", "password");

Estou usando a versão 0.0.28-BETA.

**Comment by ivosmn** [comment]
Bom dia @sonnenhohl 

Conseguiu utilizar a sdk?

Poderia me dizer a correção do exemplo que cito na sequencia?

	CorreiosCredenciais credenciais = new CorreiosCredenciais("seu-usuario", "sua-senha");
	
	CorreiosRastreioApi correiosApi = new CorreiosRastreioClientApi(credenciais);
	
	DetalhesRastreio pacoteRastreado =  correiosApi
		.buscaPacoteRastreadoUsandoOCodigo("codigo_do_seu_objeto")
		.emPortugues()
		.comTodosOsEventos()
		.getDetalhesRastreio();
		
	System.out.println(pacoteTraqueado);
